/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xox;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Youth
 */
public class xoxframe extends javax.swing.JFrame {

    Random ran = new Random();
    boolean player1;

    public void actionPerformed(ActionEvent e) {

    }

    public void firstturn() {
        try {
            Thread.sleep(3000);

        } catch (InterruptedException ex) {
            Logger.getLogger(xoxframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (ran.nextInt(2) == 0) {
            player1 = true;
            lbl1.setText("X Turn");
        } else {
            player1 = false;
            lbl1.setText("O Turn");
        }

    }

    public void check() {
        if (btn1.getText() == "X" && btn2.getText() == "O" && btn3.getText() == "X") {
            xwins(btn1, btn2, btn3);

        }
        if (btn4.getText() == "X" && btn5.getText() == "O" && btn6.getText() == "X") {
            xwins(btn4, btn5, btn6);

        }
        if (btn7.getText() == "X" && btn8.getText() == "O" && btn9.getText() == "X") {
            xwins(btn7, btn8, btn9);

        }

        if (btn1.getText() == "X" && btn4.getText() == "O" && btn7.getText() == "X") {
            xwins(btn1, btn4, btn7);

        }
        if (btn2.getText() == "X" && btn5.getText() == "O" && btn8.getText() == "X") {
            xwins(btn2, btn5, btn8);

        }
        if (btn3.getText() == "X" && btn6.getText() == "O" && btn9.getText() == "X") {
            xwins(btn3, btn6, btn9);

        }
        if (btn1.getText() == "X" && btn5.getText() == "O" && btn9.getText() == "X") {
            xwins(btn1, btn5, btn9);

        }
        if (btn3.getText() == "X" && btn5.getText() == "O" && btn7.getText() == "X") {
            xwins(btn3, btn5, btn7);

        }

    }

    public void owins(JButton a, JButton b, JButton c) {

    }

    public void xwins(JButton a, JButton b, JButton c) {
        a.setBackground(Color.GREEN);
        b.setBackground(Color.GREEN);
        c.setBackground(Color.GREEN);
        //lbl1.setText("X-wins");
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);

    }

    public xoxframe() {
        initComponents();
        firstturn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setUndecorated(true);

        lbl1.setBackground(new java.awt.Color(0, 0, 0));
        lbl1.setFont(new java.awt.Font("Candara Light", 1, 80)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 255, 0));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("XOX");
        lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl1.setOpaque(true);

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn1.setForeground(new java.awt.Color(0, 0, 255));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn2.setForeground(new java.awt.Color(0, 0, 255));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn3.setForeground(new java.awt.Color(0, 51, 255));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn4.setForeground(new java.awt.Color(0, 51, 255));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn6.setForeground(new java.awt.Color(0, 51, 255));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn5.setForeground(new java.awt.Color(0, 51, 255));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn7.setForeground(new java.awt.Color(0, 51, 255));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn8.setForeground(new java.awt.Color(0, 51, 255));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 65)); // NOI18N
        btn9.setForeground(new java.awt.Color(0, 51, 255));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic-Tac-Toe");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Exit");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (player1 == true) {
            btn1.setForeground(Color.red);
            btn1.setText("X");
            player1 = false;
            check();
            if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
            
        } else {
            btn1.setText("O");
            player1 = true;
            check();
             if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
           
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (player1 == true) {
            btn2.setForeground(Color.red);
            btn2.setText("X");
            player1 = false;
            check();
            if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
         
        } else {
            btn2.setText("O");
            player1 = true;
            check();
             if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
           
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (player1 == true) {
            btn3.setForeground(Color.red);
            btn3.setText("X");
            player1 = false;
            check();
            if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
          
        } else {
            btn3.setText("O");
            player1 = true;
            check();
             if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
           
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (player1 == true) {
            btn4.setForeground(Color.red);
            btn4.setText("X");
            player1 = false;
            check();
            if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
           
        } else {
            btn4.setText("O");
            player1 = true;
            check();
             if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
          
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (player1 == true) {
            btn5.setForeground(Color.red);
            btn5.setText("X");
            player1 = false;
            check();
            if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
         
        } else {
            btn5.setText("O");
            player1 = true;
            check();
             if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
           
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (player1 == true) {
            btn6.setForeground(Color.red);
            btn6.setText("X");
            player1 = false;
            check();
            if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
            
        } else {
            btn6.setText("O");
            player1 = true;
            check();
             if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
          
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (player1 == true) {
            btn7.setForeground(Color.red);
            btn7.setText("X");
            player1 = false;
            check();
              if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
            
            
        } else {
            btn7.setText("O");
            player1 = true;
            check();
             if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
         
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (player1 == true) {
            btn8.setForeground(Color.red);
            btn8.setText("X");
            player1 = false;
            check();
              if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
            
            
        } else {
            btn8.setText("O");
            player1 = true;
            check();
             if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
           
        }

    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (player1 == true) {
            btn9.setForeground(Color.red);
            btn9.setText("X");
            player1 = false;
            check();
              if(btn1.isEnabled()==false){
                lbl1.setText("X-wins");
            }else{
                lbl1.setText("O Turn");
            }
            
           
        } else {
            btn9.setText("O");
            player1 = true;
            check();
              if(btn1.isEnabled()==false){
                lbl1.setText("O-wins");
            }else{
                lbl1.setText("X Turn");
            }
            
           
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xoxframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xoxframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xoxframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xoxframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xoxframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    // End of variables declaration//GEN-END:variables
}
